// Generated by CoffeeScript 1.3.3
(function() {
  var OAuth, async, facebookClient, request;

  async = require("async");

  request = require("request");

  OAuth = require("oauth").OAuth;

  facebookClient = function(keys) {
    var self;
    self = this;
    this.appId = keys.appId;
    this.appSecret = keys.appSecret;
    this.requestFunctions = {
      contacts: function(tokens, cb) {
        return request("https://graph.facebook.com/me/friends?access_token=" + tokens.access_token, function(err, data, res) {
          var _ref;
          if (err) {
            return cb(new Error((_ref = err.data) != null ? _ref : err));
          }
          data = JSON.parse(data.body);
          return async.map(data.data, function(entry, cb) {
            var contact;
            contact = {
              id: entry.id,
              name: entry.name,
              picture: "http://graph.facebook.com/" + entry.id + "/picture",
              entry: entry
            };
            return cb(null, contact);
          }, cb);
        });
      },
      details: function(tokens, cb) {
        return request("https://graph.facebook.com/me?access_token=" + tokens.access_token, function(err, data, res) {
          var _ref;
          if (err) {
            return cb(new Error((_ref = err.data) != null ? _ref : err));
          }
          return cb(null, JSON.parse(data.body));
        });
      }
    };
  };

  module.exports = facebookClient;

}).call(this);
