// Generated by CoffeeScript 1.3.3
(function() {
  var facebook;

  facebook = function() {
    this.requestFunctions = {
      contacts: function(tokens, cb) {
        return cb(null, 'facebook contacts');
      },
      details: function(tokens, cb) {
        return cb(null, 'facebook details');
      }
    };
  };

  module.exports = facebook;

}).call(this);
