// Generated by CoffeeScript 1.3.3
(function() {
  var OAuth, async, facebookClient, request;

  async = require("async");

  request = require("request");

  OAuth = require("oauth").OAuth;

  facebookClient = function(keys) {
    var self;
    self = this;
    this.appId = keys.appId;
    this.appSecret = keys.appSecret;
    this.requestFunctions = {
      contacts: function(tokens, cb) {
        return request("https://graph.facebook.com/me/friends?access_token=" + tokens.access_token, function(err, response, body) {
          if (err) {
            return cb(null, {
              error: err
            });
          }
          body = JSON.parse(response.body);
          if (body.error != null) {
            return cb(null, {
              error: body.error
            });
          }
          return async.map(body.data, function(entry, cb) {
            var contact;
            contact = {
              id: entry.id,
              name: entry.name,
              picture: "http://graph.facebook.com/" + entry.id + "/picture",
              entry: entry
            };
            return cb(null, contact);
          }, cb);
        });
      },
      details: function(tokens, cb) {
        return request("https://graph.facebook.com/me?access_token=" + tokens.access_token, function(err, response, body) {
          if (err) {
            return cb(null, {
              error: err
            });
          }
          body = JSON.parse(body);
          if (body.error != null) {
            return cb(null, {
              error: body.error
            });
          }
          return cb(null, body);
        });
      }
    };
  };

  module.exports = facebookClient;

}).call(this);
