// Generated by CoffeeScript 1.3.3
(function() {
  var Gdata, google;

  Gdata = require('gdata').GDClient;

  google = function(keys) {
    var self;
    self = this;
    this.consumerKey = keys.consumerKey;
    this.consumerSecret = keys.consumerSecret;
    this.requestFunctions = {
      contacts: function(tokens, cb) {
        google = new Gdata(self.consumerKey, self.consumerSecret);
        google.setAccessToken(tokens.access_token, tokens.access_token_secret);
        return google.get('https://www.google.com/m8/feeds/contacts/default/full/', function(err, feed) {
          var contact, contacts, entry, _i, _len, _ref, _ref1;
          if (err) {
            return cb(err);
          }
          contacts = [];
          _ref = feed.getEntries();
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            entry = _ref[_i];
            contact = {
              entry: entry,
              fullname: entry.entry['gd$name']['gd$fullName'] != null,
              email: ((_ref1 = entry.entry['gd$name']) != null ? _ref1['gd$email'] : void 0) != null
            };
            contacts.push(contact);
            console.log(contact.fullname);
            console.log(contact.email);
          }
          return cb(null, 'google contacts');
        });
      },
      details: function(tokens, cb) {
        return cb(null, 'google details');
      }
    };
  };

  module.exports = google;

}).call(this);
