// Generated by CoffeeScript 1.3.3
(function() {
  var OAuth, async, request, twitterClient;

  async = require('async');

  request = require('request');

  OAuth = require('oauth').OAuth;

  twitterClient = function(keys) {
    var oauth, self;
    self = this;
    this.consumerKey = keys.consumerKey;
    this.consumerSecret = keys.consumerSecret;
    oauth = new OAuth(null, null, this.consumerKey, this.consumerSecret, '1.0', null, 'HMAC-SHA1');
    this.requestFunctions = {
      contacts: function(tokens, cb) {
        return oauth.get('https://api.twitter.com/1.1/friends/ids.json', tokens.access_token, tokens.access_token_secret, function(err, data) {
          var ids, _ref;
          if (err) {
            return cb(null, {error: new Error((_ref = err.data) != null ? _ref : err)});
          }
          data = JSON.parse(data);
          ids = data.ids.slice(0, 100).join(',');
          return oauth.get("https://api.twitter.com/1.1/users/lookup.json?user_id=" + ids, tokens.access_token, tokens.access_token_secret, function(err, data) {
            var _ref1;
            if (err) {
              return cb(new Error((_ref1 = err.data) != null ? _ref1 : err));
            }
            data = JSON.parse(data);
            return async.map(data, function(entry, cb) {
              var contact;
              contact = {
                id: entry.id,
                name: entry.name,
                picture: entry.profile_image_url,
                username: entry.screen_name,
                entry: entry
              };
              return cb(null, contact);
            }, cb);
          });
        });
      },
      details: function(tokens, cb) {
        return oauth.get('https://api.twitter.com/1.1/account/verify_credentials.json', tokens.access_token, tokens.access_token_secret, function(err, data) {
          var _ref;
          if (err) {
            return cb(null, {error: new Error((_ref = err.data) != null ? _ref : err)});
          }
          data = JSON.parse(data);
          data.username = data.screen_name;
          return cb(null, data);
        });
      }
    };
  };

  module.exports = twitterClient;

}).call(this);
